const MANAGEMENT_OF_FIELD_ACTIVITIES_TYPES = {
  GET_ALL_ACTIVITIES: 'GET_ALL_ACTIVITIES',
  GET_ALL_ACTIVITIES_SUCCESS: 'GET_ALL_ACTIVITIES_SUCCESS',
  GET_ALL_ACTIVITIES_ERROR: 'GET_ALL_ACTIVITIES_ERROR',
  RESET_GET_ALL_ACTIVITY: 'RESET_GET_ALL_ACTIVITY',

  GET_FIELD_LOGS_BY_TASK: 'GET_FIELD_LOGS_BY_TASK',
  GET_FIELD_LOGS_BY_TASK_SUCCESS: 'GET_FIELD_LOGS_BY_TASK_SUCCESS',
  GET_FIELD_LOGS_BY_TASK_ERROR: 'GET_FIELD_LOGS_BY_TASK_ERROR',

  CHANGE_FIELD_LOG_STATUS: 'CHANGE_FIELD_LOG_STATUS',
  CHANGE_FIELD_LOG_STATUS_ERROR: 'CHANGE_FIELD_LOG_STATUS_ERROR',
  CHANGE_FIELD_LOG_STATUS_SUCCESS: 'CHANGE_FIELD_LOG_STATUS_SUCCESS',
  RESET_CHANGE_FIELD_LOG_STATUS: 'RESET_CHANGE_FIELD_LOG_STATUS',
};

export default MANAGEMENT_OF_FIELD_ACTIVITIES_TYPES;
