const MANAGEMENT_OF_FIELD_ACTIVITIES_TYPES = {
  GET_ALL_ACTIVITIES: 'GET_ALL_ACTIVITIES',
  GET_ALL_ACTIVITIES_SUCCESS: 'GET_ALL_ACTIVITIES_SUCCESS',
  GET_ALL_ACTIVITIES_ERROR: 'GET_ALL_ACTIVITIES_ERROR',
  RESET_GET_ALL_ACTIVITY: 'RESET_GET_ALL_ACTIVITY',
};

export default MANAGEMENT_OF_FIELD_ACTIVITIES_TYPES;
