const MANAGEMENT_OF_FIELD_ACTIVITIES_TYPES = {
  GET_ALL_ACTIVITIES: 'GET_ALL_ACTIVITIES',
  GET_ALL_ACTIVITIES_SUCCESS: 'GET_ALL_ACTIVITIES_SUCCESS',
  GET_ALL_ACTIVITIES_ERROR: 'GET_ALL_ACTIVITIES_ERROR',
  RESET_GET_ALL_ACTIVITY: 'RESET_GET_ALL_ACTIVITY',

  GET_FIELD_LOGS_BY_TASK: 'GET_FIELD_LOGS_BY_TASK',
  GET_FIELD_LOGS_BY_TASK_SUCCESS: 'GET_FIELD_LOGS_BY_TASK_SUCCESS',
  GET_FIELD_LOGS_BY_TASK_ERROR: 'GET_FIELD_LOGS_BY_TASK_ERROR',

  CHANGE_FIELD_LOG_STATUS: 'CHANGE_FIELD_LOG_STATUS',
  CHANGE_FIELD_LOG_STATUS_ERROR: 'CHANGE_FIELD_LOG_STATUS_ERROR',
  CHANGE_FIELD_LOG_STATUS_SUCCESS: 'CHANGE_FIELD_LOG_STATUS_SUCCESS',
  RESET_CHANGE_FIELD_LOG_STATUS: 'RESET_CHANGE_FIELD_LOG_STATUS',

  GET_ALL_CONTROL_ACTIVITY: 'GET_ALL_CONTROL_ACTIVITY',
  GET_ALL_CONTROL_ACTIVITY_SUCCESS: 'GET_ALL_CONTROL_ACTIVITY_SUCCESS',
  GET_ALL_CONTROL_ACTIVITY_ERROR: 'GET_ALL_CONTROL_ACTIVITY_ERROR',

  GET_CONTROL_ACTIVITY_PARAMS: 'GET_CONTROL_ACTIVITY_PARAMS',
  GET_CONTROL_ACTIVITY_PARAMS_SUCCESS: 'GET_CONTROL_ACTIVITY_PARAMS_SUCCESS',
  GET_CONTROL_ACTIVITY_PARAMS_ERROR: 'GET_CONTROL_ACTIVITY_PARAMS_ERROR',

  HANDLE_CONTROL_ACTIVITY_DATA_EDIT: 'HANDLE_CONTROL_ACTIVITY_DATA_EDIT',
  HANDLE_CONTROL_ACTIVITY_DATA_ADD: 'HANDLE_CONTROL_ACTIVITY_DATA_ADD',
};

export default MANAGEMENT_OF_FIELD_ACTIVITIES_TYPES;
