const ROUTES = {
  ERROR: '404',
  UNAVAILABLE: '*',
  MAIN: '/',
  HOME: '/home',
  SIGN_UP: '/signup',
  SIGN_IN: '/signin',
  FORM: '/form',
  USER: '/form/user',
  TEST: '/test',
  USER_ROLES: '/pannel/user-roles',
  COMPANY_MANAGEMENT: 'company-management',
  PROJECT_MANAGEMENT: 'project-management',
  IMPORT_PROJECT_DATA: 'import-project-data',
  WORKLIST_MANAGEMENT: 'worklist-management',
  ASSIGN_WORK_ACTIVITIES: 'assign-work-activities',
  ACTIVITIES_MANAGEMENT: 'activities-management',
  MILESTONE_APPROVAl: 'milestone-approval',
  ECM_SERVICES: 'ecm-services',
  WEB_GIS_SERVICES: 'web-gis-services',
  WEBEX: 'webex',
  FEEDBACK_SERVICES: 'feedback-services',
  PANNEL: 'pannel',
};

export default ROUTES;
