const ASSIGN_WORK_ACTIVITY_TYPE = {
  SELECT_ALL: 'SELECT_ALL',
  DESELECT_ALL: 'DESELECT_ALL',

  SELECT_ONE: 'SELECT_ONE',
  DESELECT_ONE: 'DESELECT_ONE',
};

export default ASSIGN_WORK_ACTIVITY_TYPE;
