const ASSIGN_WORK_ACTIVITY_TYPE = {
  SELECT_ALL: 'SELECT_ALL',
  DESELECT_ALL: 'DESELECT_ALL',

  SELECT_ONE: 'SELECT_ONE',
  DESELECT_ONE: 'DESELECT_ONE',

  ASSIGN_TASK: 'ASSIGN_TASK',
  ASSIGN_TASK_SUCCESS: 'ASSIGN_TASK_SUCCESS',
  ASSIGN_TASK_ERROR: 'ASSIGN_TASK_ERROR',
  RESET_ASSIGN_TASK: 'RESET_ASSIGN_TASK',
};

export default ASSIGN_WORK_ACTIVITY_TYPE;
