const FEEDBACK_ACTIONS_TYPES = {
  ADD_NEW_FEEDBACK: 'ADD_NEW_FEEDBACK',
  ADD_NEW_FEEDBACK_SUCCESS: 'ADD_NEW_FEEDBACK_SUCCESS',
  ADD_NEW_FEEDBACK_ERROR: 'ADD_NEW_FEEDBACK_ERROR',
  RESET_ADD_NEW_FEEDBACK: 'RESET_ADD_NEW_FEEDBACK',

  EDIT_NEW_FEEDBACK: 'EDIT_NEW_FEEDBACK',
  EDIT_NEW_FEEDBACK_SUCCESS: 'EDIT_NEW_FEEDBACK_SUCCESS',
  EDIT_NEW_FEEDBACK_ERROR: 'EDIT_NEW_FEEDBACK_ERROR',
  RESET_EDIT_FEEDBACK: 'RESET_EDIT_FEEDBACK',

  DELETE_FEEDBACK: 'DELETE_FEEDBACK',
  DELETE_FEEDBACK_SUCCESS: 'DELETE_FEEDBACK_SUCCESS',
  DELETE_FEEDBACK_ERROR: 'DELETE_FEEDBACK_ERROR',
  RESET_DELETE_FEEDBACK: 'RESET_DELETE_FEEDBACK',

  GET_ALL_FEEDBACK: 'GET_ALL_FEEDBACK',
  GET_ALL_FEEDBACK_SUCCESS: 'GET_ALL_FEEDBACK_SUCCESS',
  GET_ALL_FEEDBACK_ERROR: 'GET_ALL_FEEDBACK_ERROR',
  RESET_GET_ALL_FEEDBACK: 'RESET_GET_ALL_FEEDBACK',
};

export default FEEDBACK_ACTIONS_TYPES;
