const COMPANY_MANAGEMENT = {
  ADD: 'ADD',
  CANCEL: 'CANCEL',
  ADD_COMPANY_SUCCESS: 'ADD_COMPANY_SUCCESS',
  ADD_COMPANY_START: 'ADD_COMPANY_START',
  ADD_COMPANY_ERROR: 'ADD_COMPANY_ERROR',
  GET_COMPANIES: 'GET_COMPANIES',
  GET_COMPANIES_ERROR: 'GET_COMPANIES_ERROR ',
  GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
};

export default COMPANY_MANAGEMENT;
