const COMPANY_MANAGEMENT = {
  ADD: 'ADD',
  CANCEL: 'CANCEL',
  CREATE: 'CREATE',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  START: 'START',
  GET_COMPANIES: 'GET_COMPANIES',
  GET_COMPANIES_ERROR: 'GET_COMPANIES_ERROR ',
  GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
};

export default COMPANY_MANAGEMENT;
