const COMPANY_MANAGEMENT = {
  ADD: 'ADD',
  CANCEL: 'CANCEL',
};

export default COMPANY_MANAGEMENT;

//  CREATE: 'CREATE',
// ADD_USER: 'ADD_USER',
// COMPANY_DETAILS: 'COMPANY_DETAILS',
// USERS: 'USERS',
