const WEBEX_ACTION_TYPES = {
  GET_WEBEX_AUTH_START: 'GET_WEBEX_AUTH_START',
  GET_WEBEX_ACCESSTOKEN: 'GET_WEBEX_ACCESSTOKEN',
  GET_WEBEX_ACCESSTOKEN_VALID: 'GET_WEBEX_ACCESSTOKEN_VALID',
  GET_WEBEX_ACCESSTOKEN_REQ: 'GET_WEBEX_ACCESSTOKEN_REQ',
  GET_WEBEX_ROOMS: 'GET_WEBEX_ROOMS',
  GET_WEBEX_ROOMS_SUCCESS: 'GET_WEBEX_ROOMS_SUCCESS',
  GET_WEBEX_ROOMS_ERROR: 'GET_WEBEX_ROOMS_ERROR',
};

export default WEBEX_ACTION_TYPES;
