const WEBEX_ACTION_TYPES = {
  GET_WEBEX_AUTH_START: 'GET_WEBEX_AUTH_START',
  GET_WEBEX_ACCESSTOKEN: 'GET_WEBEX_ACCESSTOKEN',
  GET_WEBEX_ACCESSTOKEN_VALID: 'GET_WEBEX_ACCESSTOKEN_VALID',
  GET_WEBEX_ACCESSTOKEN_REQ: 'GET_WEBEX_ACCESSTOKEN_REQ',
  GET_WEBEX_ROOMS: 'GET_WEBEX_ROOMS',
  GET_WEBEX_ROOMS_SUCCESS: 'GET_WEBEX_ROOMS_SUCCESS',
  GET_WEBEX_ROOMS_ERROR: 'GET_WEBEX_ROOMS_ERROR',

  ADD_WEBEX_MESSAGE: 'ADD_WEBEX_MESSAGE',
  ADD_WEBEX_MESSAGE_SUCCESS: 'ADD_WEBEX_MESSAGE_SUCCESS',
  ADD_WEBEX_MESSAGE_ERROR: 'ADD_WEBEX_MESSAGE_ERROR',
  RESET_WEBEX_MESSAGE: 'RESET_WEBEX_MESSAGE',

  ADD_WEBEX_FILE: 'ADD_WEBEX_FILE',
  ADD_WEBEX_FILE_SUCCESS: 'ADD_WEBEX_FILE_SUCCESS',
  ADD_WEBEX_FILE_ERROR: 'ADD_WEBEXFILEE_ERROR',
  RESET_WEBEX_FILE: 'RESET_WEBEX_FILE',
};

export default WEBEX_ACTION_TYPES;
