const MILESTONE_MANAGEMENT_ACTION_TYPES = {
  GET_ALL_MILESTONES: 'GET_ALL_MILESTONES',
  GET_ALL_MILESTONES_SUCCESS: 'GET_ALL_MILESTONES_SUCCESS',
  GET_ALL_MILESTONES_ERROR: 'GET_ALL_MILESTONES_ERROR',

  UPDATE_MILESTONE: 'UPDATE_MILESTONE',
  UPDATE_MILESTONE_SUCCESS: 'UPDATE_MILESTONE_SUCCESS',
  UPDATE_MILESTONE_ERROR: 'UPDATE_MILESTONE_ERROR',

  GET_MILESTONE_BY_ID: 'GET_MILESTONE_BY_ID',
  GET_MILESTONE_BY_ID_SUCCESS: 'GET_MILESTONE_BY_ID_SUCCESS',
  GET_MILESTONE_BY_ID_ERROR: 'GET_MILESTONE_BY_ID_ERROR',
};

export default MILESTONE_MANAGEMENT_ACTION_TYPES;
